variables:
  GIT_SUBMODULE_STRATEGY: normal
  MOSQUITTO_IMAGE: $CI_REGISTRY_IMAGE/mosquitto
  EXAMPLE_DRIVER_IMAGE: $CI_REGISTRY_IMAGE/example-driver
  EXAMPLE_APPLICATION_IMAGE: $CI_REGISTRY_IMAGE/example-application
  # required CI env input: DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD
  DOCKER_HUB_IMAGE: mf2c/sensor-manager
  DOCKER_HUB_IMAGE_MOSQUITTO: mf2c/sensor-manager-mosquitto
  DOCKER_HUB_IMAGE_EXAMPLE_DRIVER: mf2c/sensor-manager-example-driver
  DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION: mf2c/sensor-manager-example-application

stages:
  - compile
  # not referenced from upstream here to make this standalone on github
  - container
  - publish

job-compile-x86_64:
  stage: compile
  image: golang:1.12.0-alpine3.9
  script:
    - apk add git
    - go build -o bin/sensor-manager sensor-manager.go
    - go build -o bin/example-driver example-driver.go
    - go build -o bin/example-application example-application.go
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-x86_64"
    paths:
      - bin/
  variables:
    GOARCH: amd64
    GOOS: linux

job-compile-armhf:
  stage: compile
  image: golang:1.12.0-alpine3.9
  script:
    - apk add git
    - go build -o bin/sensor-manager sensor-manager.go
    - go build -o bin/example-driver example-driver.go
    - go build -o bin/example-application example-application.go
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-armhf"
    paths:
      - bin/
  variables:
    GOARCH: arm
    GOOS: linux
    GOARM: 7

docker-image-x86_64:
  stage: container
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest-x86_64 --cache-from $CI_REGISTRY_IMAGE:latest-x86_64 -f Dockerfile-sensor-manager .
    - docker build -t $MOSQUITTO_IMAGE:latest-x86_64 --cache-from $MOSQUITTO_IMAGE:latest-x86_64 -f Dockerfile-mqtt-auth .
    - docker build -t $EXAMPLE_DRIVER_IMAGE:latest-x86_64 --cache-from $EXAMPLE_DRIVER_IMAGE:latest-x86_64 -f Dockerfile-example-driver .
    - docker build -t $EXAMPLE_APPLICATION_IMAGE:latest-x86_64 --cache-from $EXAMPLE_APPLICATION_IMAGE:latest-x86_64 -f Dockerfile-example-application .
    - docker push $CI_REGISTRY_IMAGE:latest-x86_64
    - docker push $MOSQUITTO_IMAGE:latest-x86_64
    - docker push $EXAMPLE_DRIVER_IMAGE:latest-x86_64
    - docker push $EXAMPLE_APPLICATION_IMAGE:latest-x86_64
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:stable-dind
  only:
    - /^master$/
  dependencies:
    - job-compile-x86_64

docker-image-armhf:
  stage: container
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest-armhf --cache-from $CI_REGISTRY_IMAGE:latest-armhf -f Dockerfile-sensor-manager .
    - docker build -t $MOSQUITTO_IMAGE:latest-armhf --cache-from $MOSQUITTO_IMAGE:latest-armhf -f Dockerfile-mqtt-auth .
    - docker build -t $EXAMPLE_DRIVER_IMAGE:latest-armhf --cache-from $EXAMPLE_DRIVER_IMAGE:latest-armhf -f Dockerfile-example-driver .
    - docker build -t $EXAMPLE_APPLICATION_IMAGE:latest-armhf --cache-from $EXAMPLE_APPLICATION_IMAGE:latest-armhf -f Dockerfile-example-application .
    - docker push $CI_REGISTRY_IMAGE:latest-armhf
    - docker push $MOSQUITTO_IMAGE:latest-armhf
    - docker push $EXAMPLE_DRIVER_IMAGE:latest-armhf
    - docker push $EXAMPLE_APPLICATION_IMAGE:latest-armhf
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:stable-dind
  only:
    - /^master$/
  tags:
    - armv7l
  dependencies:
    - job-compile-armhf

publish-crossplatform-gitlab:
  stage: publish
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # enable experimental features for the manifest
    - apk add jq
    - "jq '. + {experimental: \"enabled\"}' ~/.docker/config.json > ~/.docker/config.json.temp"
    - mv ~/.docker/config.json.temp ~/.docker/config.json
    # create a list (manifest) of all images
    - docker manifest create $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest-x86_64 $CI_REGISTRY_IMAGE:latest-armhf
    - docker manifest annotate $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest-x86_64 --arch amd64
    - docker manifest annotate $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest-armhf --arch arm
    - docker manifest push $CI_REGISTRY_IMAGE:latest
    # repeat for mosquitto
    - docker manifest create $MOSQUITTO_IMAGE:latest $MOSQUITTO_IMAGE:latest-x86_64 $MOSQUITTO_IMAGE:latest-armhf
    - docker manifest annotate $MOSQUITTO_IMAGE:latest $MOSQUITTO_IMAGE:latest-x86_64 --arch amd64
    - docker manifest annotate $MOSQUITTO_IMAGE:latest $MOSQUITTO_IMAGE:latest-armhf --arch arm
    - docker manifest push $MOSQUITTO_IMAGE:latest
    # repeat for the example driver
    - docker manifest create $EXAMPLE_DRIVER_IMAGE:latest $EXAMPLE_DRIVER_IMAGE:latest-x86_64 $EXAMPLE_DRIVER_IMAGE:latest-armhf
    - docker manifest annotate $EXAMPLE_DRIVER_IMAGE:latest $EXAMPLE_DRIVER_IMAGE:latest-x86_64 --arch amd64
    - docker manifest annotate $EXAMPLE_DRIVER_IMAGE:latest $EXAMPLE_DRIVER_IMAGE:latest-armhf --arch arm
    - docker manifest push $EXAMPLE_DRIVER_IMAGE:latest
    # repeat for the example application
    - docker manifest create $EXAMPLE_APPLICATION_IMAGE:latest $EXAMPLE_APPLICATION_IMAGE:latest-x86_64 $EXAMPLE_APPLICATION_IMAGE:latest-armhf
    - docker manifest annotate $EXAMPLE_APPLICATION_IMAGE:latest $EXAMPLE_APPLICATION_IMAGE:latest-x86_64 --arch amd64
    - docker manifest annotate $EXAMPLE_APPLICATION_IMAGE:latest $EXAMPLE_APPLICATION_IMAGE:latest-armhf --arch arm
    - docker manifest push $EXAMPLE_APPLICATION_IMAGE:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:stable-dind
  only:
    - /^master$/

publish-crossplatform-dockerhub:
  stage: publish
  image: docker:stable
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # enable experimental features for the manifest
    - apk add jq
    - "jq '. + {experimental: \"enabled\"}' ~/.docker/config.json > ~/.docker/config.json.temp"
    - mv ~/.docker/config.json.temp ~/.docker/config.json
    # pull, tag local, push and create a list (manifest) of all images
    - docker pull $CI_REGISTRY_IMAGE:latest-x86_64
    - docker pull $CI_REGISTRY_IMAGE:latest-armhf
    - docker tag $CI_REGISTRY_IMAGE:latest-x86_64 $DOCKER_HUB_IMAGE:latest-x86_64
    - docker tag $CI_REGISTRY_IMAGE:latest-armhf $DOCKER_HUB_IMAGE:latest-armhf
    - docker push $DOCKER_HUB_IMAGE:latest-x86_64
    - docker push $DOCKER_HUB_IMAGE:latest-armhf
    - docker manifest create $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:latest-x86_64 $DOCKER_HUB_IMAGE:latest-armhf
    - docker manifest annotate $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:latest-x86_64 --arch amd64
    - docker manifest annotate $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:latest-armhf --arch arm
    - docker manifest push $DOCKER_HUB_IMAGE:latest
    # repeat for mosquitto
    - docker pull $MOSQUITTO_IMAGE:latest-x86_64
    - docker pull $MOSQUITTO_IMAGE:latest-armhf
    - docker tag $MOSQUITTO_IMAGE:latest-x86_64 $DOCKER_HUB_IMAGE_MOSQUITTO:latest-x86_64
    - docker tag $MOSQUITTO_IMAGE:latest-armhf $DOCKER_HUB_IMAGE_MOSQUITTO:latest-armhf
    - docker push $DOCKER_HUB_IMAGE_MOSQUITTO:latest-x86_64
    - docker push $DOCKER_HUB_IMAGE_MOSQUITTO:latest-armhf
    - docker manifest create $DOCKER_HUB_IMAGE_MOSQUITTO:latest $DOCKER_HUB_IMAGE_MOSQUITTO:latest-x86_64 $DOCKER_HUB_IMAGE_MOSQUITTO:latest-armhf
    - docker manifest annotate $DOCKER_HUB_IMAGE_MOSQUITTO:latest $DOCKER_HUB_IMAGE_MOSQUITTO:latest-x86_64 --arch amd64
    - docker manifest annotate $DOCKER_HUB_IMAGE_MOSQUITTO:latest $DOCKER_HUB_IMAGE_MOSQUITTO:latest-armhf --arch arm
    - docker manifest push $DOCKER_HUB_IMAGE_MOSQUITTO:latest
    # repeat for the example driver
    - docker pull $EXAMPLE_DRIVER_IMAGE:latest-x86_64
    - docker pull $EXAMPLE_DRIVER_IMAGE:latest-armhf
    - docker tag $EXAMPLE_DRIVER_IMAGE:latest-x86_64 $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-x86_64
    - docker tag $EXAMPLE_DRIVER_IMAGE:latest-armhf $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-armhf
    - docker push $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-x86_64
    - docker push $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-armhf
    - docker manifest create $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-x86_64 $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-armhf
    - docker manifest annotate $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-x86_64 --arch amd64
    - docker manifest annotate $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest-armhf --arch arm
    - docker manifest push $DOCKER_HUB_IMAGE_EXAMPLE_DRIVER:latest
    # repeat for the example application
    - docker pull $EXAMPLE_APPLICATION_IMAGE:latest-x86_64
    - docker pull $EXAMPLE_APPLICATION_IMAGE:latest-armhf
    - docker tag $EXAMPLE_APPLICATION_IMAGE:latest-x86_64 $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-x86_64
    - docker tag $EXAMPLE_APPLICATION_IMAGE:latest-armhf $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-armhf
    - docker push $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-x86_64
    - docker push $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-armhf
    - docker manifest create $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-x86_64 $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-armhf
    - docker manifest annotate $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-x86_64 --arch amd64
    - docker manifest annotate $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest-armhf --arch arm
    - docker manifest push $DOCKER_HUB_IMAGE_EXAMPLE_APPLICATION:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:stable-dind
  only:
    - /^master$/
