version: "3.5"
services:
  mosquitto:
    image: mf2c/sensor-manager-mosquitto:latest
    ports:
      - 8080:8080
    environment:
      - "MOSQUITTO_WEBSOCKETS_PORT=8080"
      - "MOSQUITTO_AUTH_HTTP_HOST=sensor-manager"
      - "MOSQUITTO_AUTH_HTTP_PORT=8080"
  sensor-manager:
    image: mf2c/sensor-manager:latest
    depends_on:
      - mosquitto
    ports:
      - 8081:8080
    environment:
      - "MQTT_HOST=mosquitto"
      - "MQTT_PORT=8080"
      - "CIMI_HOST=traefik"
      - "CIMI_PORT=443"
      - "LIFECYCLE_HOST=lifecycle"
      - "LIFECYCLE_PORT=46000"
      - "HTTP_PORT=8080"
      - "AUTH_DB_FILE=/data/authdb.json"
      - "ADMINISTRATOR_ACCESS_TOKEN=thisisaverysecureadministratortokenplsnocrack"
      - "SENSOR_DRIVER_ACCESS_TOKEN=thisisaverysecuresensordrivertokenplsnocrack"
      - "APPLICATION_SECRET=thisisaverysecureapplicationsecretplsnocrack"
      - "SENSORS_CHECK_INTERVAL_SECONDS=5"
      - "SENSOR_CONTAINER_MAP_FILE=/data/sensor-container-map.json"
      - "SENSOR_DRIVER_DOCKER_NETWORK_NAME=mf2c_default"
