version: "3.5"
services:
  mosquitto:
    image: registry-gitlab.xlab.si/mf2c/sensor-manager/mosquitto:latest
    ports:
      - 1883:1883
    environment:
      - "MOSQUITTO_AUTH_HTTP_HOST=sensor-manager"
      - "MOSQUITTO_AUTH_HTTP_PORT=8080"
  sensor-manager:
    image: registry-gitlab.xlab.si/mf2c/sensor-manager:latest
    depends_on:
      - mosquitto
    ports:
      - 8080:8080
    environment:
      - "MQTT_HOST=mosquitto"
      - "MQTT_PORT=1883"
      - "CIMI_HOST=traefik"
      - "CIMI_PORT=443"
      - "LIFECYCLE_HOST=lifecycle"
      - "LIFECYCLE_PORT=46000"
      - "HTTP_PORT=8080"
      - "AUTH_DB_FILE=/data/authdb.json"
      - "ADMINISTRATOR_ACCESS_TOKEN=thisisaverysecureadministratortokenplsnocrack"
      - "SENSOR_DRIVER_ACCESS_TOKEN=thisisaverysecuresensordrivertokenplsnocrack"
      - "APPLICATION_SECRET=thisisaverysecureapplicationsecretplsnocrack"
